name: scp files
on: [push]
jobs:
    build:
        name: Build
        environment: HOST
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: clen the server directory
              uses: appleboy/ssh-action@v1.0.2
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: rm -rf /home/diwi/serverCI/
            - name: copy file via ssh
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  source: ${{ github.workspace }}/*
                  target: "/home/diwi/serverCI"
            - name: run the server
              uses: appleboy/ssh-action@v1.0.2
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: cd /home/diwi/serverCI/github/workspace && npm install && pm2 delete server && pm2 start server.js
